kind: Secret
apiVersion: v1
metadata:
  name: <image-pull-secret>
  namespace: default #this can any namespace or be left out if no
data:
  .dockerconfigjson: >-
    <your-config-file-secret>
type: kubernetes.io/dockerconfigjson